sudo: required
services:
 - docker

before_install:
        - docker build -t mojoboss/docker-react:latest -f Dockerfile.dev .
script:
        - docker run -e CI=true mojoboss/docker-react:latest npm run test -- --coverage
language: generic
