sudo: required
services:
 - docker

before_install:
        - docker build -t mojoboss/docker-react:latest -f Dockerfile.dev .
script:
        - docker run -e CI=true mojoboss/docker-react:latest npm run test -- --coverage
language: generic

deploy:
 provider: elasticbeanstalk
 region: "ap-south-1"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-ap-south-1-297338036530"
 bucket_path: "docker-react"
 on:
   branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
